/**
 * reviewer.js — auto-review for opened PRs.
 *
 * Combines deterministic diff rules with a Zayvora LLM critic.
 * Rule blocks override the LLM verdict (fail-safe).
 */

import { getPrFiles, postPrComment } from './git.js';
import { callZayvora } from './zayvora-bridge.js';

const SECRET_PATTERNS = [
  /AKIA[0-9A-Z]{16}/,
  /ghp_[A-Za-z0-9]{36}/,
  /gho_[A-Za-z0-9]{36}/,
  /sk-[A-Za-z0-9]{20,}/,
  /-----BEGIN (RSA |EC |OPENSSH |DSA |)PRIVATE KEY-----/,
];

const BANNED_PATH_RES = [
  /^\.github\/workflows\//,
  /^node_modules\//,
  /(^|\/)\.env(\.|$)/,
  /\.pem$/,
];

export function runDiffRules(files, config) {
  const blocks = [];
  const totalLoc = files.reduce((s, f) => s + (f.changes || 0), 0);
  const maxLoc = config.reviewMaxDiffLoc || 1500;
  const maxFiles = config.reviewMaxFiles || 25;

  if (totalLoc > maxLoc) {
    blocks.push(`diff too large: ${totalLoc} LOC > ${maxLoc}`);
  }
  if (files.length > maxFiles) {
    blocks.push(`too many files: ${files.length} > ${maxFiles}`);
  }
  for (const f of files) {
    for (const re of BANNED_PATH_RES) {
      if (re.test(f.filename)) {
        blocks.push(`banned path: ${f.filename}`);
        break;
      }
    }
    for (const re of SECRET_PATTERNS) {
      if (re.test(f.patch || '')) {
        blocks.push(`secret pattern in ${f.filename}`);
        break;
      }
    }
  }
  return blocks;
}

function buildDiffText(files) {
  let buf = '';
  for (const f of files) {
    if (!f.patch) continue;
    buf += `\n--- ${f.filename} (${f.status}, +${f.additions} -${f.deletions})\n${f.patch}\n`;
    if (buf.length > 12000) { buf = buf.slice(0, 12000) + '\n…[truncated]'; break; }
  }
  return buf || '(no patch text available)';
}

function parseCritic(raw) {
  const cleaned = String(raw || '').replace(/```json\s*|```/g, '').trim();
  const match = cleaned.match(/\{[\s\S]*\}/);
  try {
    const o = JSON.parse(match ? match[0] : cleaned);
    if (!['approve', 'request_changes'].includes(o.verdict)) throw new Error('bad verdict');
    return {
      verdict: o.verdict,
      severity: ['low', 'medium', 'high'].includes(o.severity) ? o.severity : 'medium',
      reasons: Array.isArray(o.reasons) ? o.reasons.slice(0, 5).map(String) : [],
    };
  } catch {
    return {
      verdict: 'request_changes',
      severity: 'high',
      reasons: ['critic output unparseable — failing safe'],
    };
  }
}

export async function runLlmCritic({ prTitle, prBody, files, config }) {
  const totalLoc = files.reduce((s, f) => s + (f.changes || 0), 0);
  const diff = buildDiffText(files);

  const prompt = [
    `You are Zayvora, acting as a strict senior code reviewer. Review the following GitHub PR diff for: correctness, secret leakage, hardcoded credentials, scope creep, obvious bugs, and missing error handling.`,
    ``,
    `PR title: ${prTitle || '(untitled)'}`,
    `PR description: ${(prBody || '').slice(0, 500)}`,
    `Files changed: ${files.length}, total LOC: ${totalLoc}`,
    ``,
    `DIFF:`,
    diff,
    ``,
    `Respond ONLY with a single JSON object on one line. No prose, no markdown fences. Schema:`,
    `{"verdict":"approve"|"request_changes","severity":"low"|"medium"|"high","reasons":["short bullet",...]}`,
    `Maximum 5 reasons. If you cannot find blocking issues, return {"verdict":"approve","severity":"low","reasons":["no blocking issues found"]}.`,
  ].join('\n');

  let raw = '';
  try {
    raw = await callZayvora(prompt, config, 'critic');
  } catch (err) {
    return {
      verdict: 'request_changes',
      severity: 'high',
      reasons: [`critic call failed: ${err.message.slice(0, 120)}`],
      llmRaw: '',
    };
  }
  return { ...parseCritic(raw), llmRaw: raw };
}

export function formatReviewComment(review) {
  const head = review.verdict === 'approve'
    ? '🤖 **Auto-review: APPROVE**'
    : '🤖 **Auto-review: REQUEST CHANGES**';
  const lines = [head, `Severity: \`${review.severity}\``];
  if (review.ruleBlocks?.length) {
    lines.push('', '**Rule blocks (deterministic):**');
    for (const b of review.ruleBlocks) lines.push(`- ${b}`);
  }
  if (review.reasons?.length) {
    lines.push('', '**Critic reasons:**');
    for (const r of review.reasons) lines.push(`- ${r}`);
  }
  lines.push('', '_Generated by GN8R + Zayvora (local Ollama). Manual merge button remains available._');
  return lines.join('\n');
}

/**
 * Combined auto-review: rule blocks override the LLM verdict.
 */
export async function runAutoReview({ owner, repo, prNumber, prTitle, prBody, config, onProgress }) {
  onProgress?.('• Fetching PR files…');
  const files = await getPrFiles(owner, repo, prNumber, config);

  onProgress?.('• Diff rule checks…');
  const ruleBlocks = runDiffRules(files, config);

  onProgress?.('• Zayvora critic…');
  const llm = await runLlmCritic({ prTitle, prBody, files, config });

  let verdict = llm.verdict;
  let severity = llm.severity;
  const reasons = [...llm.reasons];

  if (ruleBlocks.length) {
    verdict = 'request_changes';
    severity = 'high';
  }

  return { verdict, severity, reasons, ruleBlocks, llmRaw: llm.llmRaw };
}

export { postPrComment };
